# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b8eab3c3-9ba8-4902-bfd5-89592cf6915c'
  imageRepository: 'stockanalysiswebsite'
  containerRegistry: 'mycontainer23registry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  azureSubscription: 'azureSubscription'
  containerGroupName: 'devopsswapp'
  containerName: 'devopsswapp'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test
  displayName: Test stage
  jobs:
  - job: Test
    displayName: Run unit tests
    pool:
      vmImage: $(vmImageName)
      parallel: 1
    steps:
    - script: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest test_login.py
      displayName: Run tests with Pytest
      
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build and push Docker image
    pool:
      vmImage: $(vmImageName)
      parallel: 1
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - task: AzureCLI@2
      displayName: 'Create container group'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container create \
            --resource-group myResourceGroup \
            --name $(containerGroupName) \
            --image $(containerRegistry)/$(imageRepository):$(tag) \
            --cpu 1 \
            --memory 1 \
            --ports 5000 \
            --ip-address public \
            --registry-login-server $(containerRegistry) \
            --registry-username 'MyContainer23Registry' \
            --registry-password 'jKYFAUenrzJkalDiMVZ511aFTyFc1fF5FstrRQV31k+ACRCevkos' \
            --dns-name-label $(containerName)
    - task: AzureCLI@2
      displayName: 'Show container group details'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container show \
            --resource-group myResourceGroup \
            --name $(containerGroupName) \
            --query "{FQDN:ipAddress.fqdn,ProvisioningState:provisioningState}" \
            --out table
